@startuml

participant ComponentList  #eaecee
participant Component  #eaecee

participant ApplicationModel #abebc6
participant QObjectListModel #abebc6

participant ApplicationViewModel #fcf3cf
participant ApplicationView #f6ddcc

participant ComponentViewModel #fcf3cf
participant ComponentView #f6ddcc

group Initialize
	loop number < ComponentList.numberOfComponents
		ApplicationModel --> ComponentList : getComponent(number)
		ComponentList --> ApplicationModel : component
		ApplicationModel --> ApplicationViewModel : signal componentAdded(component.name)
		ApplicationViewModel --> ApplicationViewModel : onComponentAdded(component.name)
	end
end

group Add Component
	ApplicationView --> ApplicationViewModel : addComponentRequest(name)
	ApplicationViewModel --> ApplicationModel : addComponent(name)
	ApplicationModel --> ComponentList : addComponent(name)
	ComponentList --> ApplicationModel : addComponentCallback(name)
	ApplicationModel --> ApplicationViewModel : signal componentAdded(name)
	ApplicationViewModel --> ApplicationViewModel : onComponentAdded(name)
end

group ApplicationViewModel.onComponentAdded
	ApplicationModel --> ComponentList : getComponent(name)
	ComponentList --> ApplicationModel : component
	ApplicationViewModel --> QObjectListModel : create ComponentViewModel and add to components list
	QObjectListModel --> ApplicationView : change property componentsList
end

group Delete Component
	ApplicationView --> ApplicationViewModel : deleteComponentRequest(name)
	ApplicationViewModel --> ApplicationModel : deleteComponent(name)
	ApplicationModel --> ComponentList : deleteComponent(name)
	ComponentList --> ApplicationModel : deleteComponentCallback(name)	
	ApplicationModel --> ApplicationViewModel : signal componentDeleted(name)
	ApplicationViewModel --> ApplicationViewModel : onComponentDeleted(name)	
end

group ApplicationViewModel.onComponentDeleted
	ApplicationViewModel --> ApplicationViewModel : find related ComponentViewModel by name
	ApplicationViewModel --> ApplicationViewModel : ComponentViewModel
	ApplicationViewModel --> QObjectListModel : delete ComponentViewModel from components list
	QObjectListModel --> ApplicationView : change property componentsList
end

group Select Component
	ApplicationView --> ApplicationViewModel : selectComponentRequest(name)
	ApplicationViewModel --> ApplicationViewModel : onComponentSelected(name)
end

group ApplicationViewModel.onComponentSelected
	ApplicationViewModel --> QObjectListModel : find ComponentViewModel by name
	QObjectListModel --> ApplicationViewModel : componentViewModel
	ApplicationViewModel --> ApplicationViewModel : selectedComponent = componentViewModel
	ApplicationViewModel --> ApplicationView : property selectedComponent
end

@enduml